# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
